### ISSUE TITLE
Add second blog page of katapult ukraine blog

### ISSUE THREAD

**Issue by johanneshiry** [factsforfriends/fff-scrapy#3]
Seems like katapult uses a second blog since today. Maybe its because they have issues regarding their live blog length. We need to check this from time to time and may add additional urls. For now its only `https://katapult-magazin.de/de/artikel/liveblog-zur-ukraine-geht-weiter`

**Comment by jenzopr** [comment]
Changes are reflected in the scheduled cloud task as well 💯
